baseURL = "https://test.ea7klk.es/"
DefaultContentLanguage = "es"
defaultContentLanguageInSubdir = false
languageCode = "es"
title = "EA7KLK- Blog de radioafición"
theme = "lightbi-hugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
#pygmentsUseClasses = true
#pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"
enableRobotsTXT = true
enableGitInfo = false
summaryLength  = "30"
ignoreLogs = ['warning-goldmark-raw-html']

[languages]
  [languages.es]
    LanguageCode  = "es"
    LanguageName = "Español"
    weight = 1
    title ="EA7KLK - Blog de radioafición"
    contentDir = "content"

[pagination]
pagerSize = 6

[Params]
selfHosted = true
mainSections = ["post","posts"]
dateFormat = "2 de enero de 2006"
comments = false
readingTime = true
wordCount = true
useHLJS = true
socialShare = true
delayDisqus = true
showRelatedPosts = true
summaryLength  = "9"
lunrSearch = true
gcse = false
lastmod = false
rss = false
pagination = "10"
hideAuthor = false
description="Mi rincón de radioafición."
previewCardImagePlacement = "bottom"
showPostImage = false

[Params.Author]
  name = "Volker Kerkhoff"
  website = "https://ea7klk.es"
  authorInfo = "Live your life as though every moment matters, because in the end, it's not the years in your life, but the life in your years that counts."
  authorPostImage = "/img/author-post-img.jpg"
  email = "volker@ea7klk.es"
  facebook = "volker.kerkhoff"
  instagram = "kerk1v"
  #youtube = "user/username" # or channel/channelname
  #twitter = "username"
  #linkedin = "username"
  github = "ea7klk"
  threads = "kerk1v"
  #gitlab = "username"  
  #reddit = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #spotify = "username"
  #paypal = "username"
  telegram = "@EA7KLK_Volker"
  #mastodon = "url"
  #slack = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #500px = "username"
  #kaggle = "username"
  #weibo = "username"
  #xing = "username"
  #bitbucket = "username"
  #soundcloud = "username"
  # codepen = "username"

[[menu.main]]
    name = "Principal"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Notas"
    url = "/notes/"
    weight = 2

[[menu.main]]
    name = "Etiquetas"
    url = "/tags/"
    weight = 3

[[menu.main]]
    name = "Enlaces"
    url = "/collections/"
    weight = 4

[[menu.main]]
    name = "Acerca de mi"
    url = "/about/"
    weight = 5


[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

